# This is a TOML document. Boom~
demoExpire = "24h"
promAddr = "http://39.105.5.227:9090"
promBasicAuthUser = "admin"
promBasicAuthPassword = "adminlwq"

# 网卡对应的主机名
netbwMapKeys = ["node-cn2","node-master"]
# 网卡速度带宽信息，单位Mbps
netbwMapValues = [1024.0,512.0]

# 本地缓存超时时间，默认30秒
localCacheExpire = 30

# 同步prom status时间间隔 cron表达式格式, "*/10 * * * * ?" 每10秒运行一次
syncStatusInterval = "*/10 * * * * ?"